### ISSUE TITLE
plsync scripts are partially broken due to some sort of python/SSL update

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/operator#32]
Originally reported by technosopher@, plsync.py appears to break due to incompatible ssl library versions.

@nkinkade what version of python are you using?

```
$ python --version
Python 2.7.6
$ ./plsync.py --help
Traceback (most recent call last):
  File "./plsync.py", line 4, in <module>
    from planetlab import session
  File "/home/soltesz/source/operator/plsync/planetlab/session.py", line 14, in <module>
    SSL_CONTEXT = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
AttributeError: 'module' object has no attribute 'SSLContext'
```

**Comment by nkinkade** [comment]
@stephen-soltesz, I'm using python 2.7.10.  From an email I sent to you and Jordan back on March 11:

=====
https://www.python.org/dev/peps/pep-0476/

This change was implemented in python 2.7.9, and not coincidentally
python was upgraded on my system from 2.7.8 to 2.7.9 just two days
ago.  A similar change was pushed out for 3.x versions.  python's
xmlrpclib now accepts a context argument [1], which can be passed the
value of ssl._create_unverified_context() to disable this new (more
secure) behavior.
=====

It would appear that my fix is not backward compatible, sadly.

**Comment by stephen-soltesz** [comment]
Was there a way to do this in the old version of Python? Or, were older versions fundamentally incapable of verifying server SSL certificates?

If this was never possible, then I'm comfortable saying that we can mark this issue as WAI, since we don't really want to support an insecure version of python.

**Comment by nkinkade** [comment]
The title of the PEP for this issue is "Enabling certificate verification by default for stdlib http clients", which would suggest to me that verification of a certificate was likely possible before but is now being enabled by default.  Do you think this should all be refactored to be backward compatible?  It may not be worth the effort since we're planning on migrating away from PLC anyway.

**Comment by pboothe** [comment]
If python with version less than 2.7.9 is needed, then we should do work.
Otherwise, I think I would happily vote for letting old versions of python
drift away and mark things WAI.

  -Peter

On Mon, Oct 19, 2015 at 5:41 PM, nkinkade <notifications@github.com> wrote:

> The title of the PEP for this issue is "Enabling certificate verification
> by default for stdlib http clients", which would suggest to me that
> verification of a certificate was likely possible before but is now being
> enabled by default. Do you think this should all be refactored to be
> backward compatible? It may not be worth the effort since we're planning on
> migrating away from PLC anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-lab/operator/issues/32#issuecomment-149355689>.
>



-- 
ᴹ̶LAB <http://measurementlab.net/> | Measure the Internet, save the data,
and make it universally accessible and useful.

**Comment by nkinkade** [comment]
I'm not aware of any reason why python <2.7.9 would be needed.  I've been using 2.7.10 with no problems (with this patch) for 6+ months now.
